kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aduit-viewer
  annotations:
    configmanagement.gke.io/cluster-selector: selector-aws
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
