kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-t-rex-ingress
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      app: t-rex-app
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 8080
